services:
  backend:
    build:
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      - PORT=80
      - JWT_SECRET=secret
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
