services:
  backend:
    build:
      dockerfile: Dockerfile
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://$POSTGRES_USER:$POSTGRES_PASSWORD@db:5432/$POSTGRES_DB
    networks:
      - app-network
  db:
    image: postgres:17
    env_file:
      - .env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
